### ISSUE TITLE
partial model missing _field_mlricheditor

### ISSUE THREAD

**Issue by Pixinside** [rainlab/blog-plugin#587]
Hello,
I'm using October 3.6.10 and the blog version 1.7.0 and I get this error:

```
SystemException: Le modèle partiel "_field_mlricheditor" est introuvable. in /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php:97
Stack trace:
#0 /Users/casashock/Documents/NovaProjects/solumat/modules/backend/widgets/Form.php(346): Backend\Classes\WidgetBase->makePartial('_field_mlriched...', Array)
#1 /Users/casashock/Documents/NovaProjects/solumat/modules/backend/widgets/form/partials/_field.php(25): Backend\Widgets\Form->renderFieldElement(Object(Backend\Classes\FormField))
#2 /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php(272): include('/Users/casashoc...')
#3 /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php(103): Backend\Classes\WidgetBase->makeFileContents('/Users/casashoc...', Array)
#4 /Users/casashock/Documents/NovaProjects/solumat/modules/backend/widgets/form/partials/_field-container.php(9): Backend\Classes\WidgetBase->makePartial('_field', Array)
#5 /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php(272): include('/Users/casashoc...')
#6 /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php(103): Backend\Classes\WidgetBase->makeFileContents('/Users/casashoc...', Array)
#7 /Users/casashock/Documents/NovaProjects/solumat/modules/backend/widgets/form/partials/_form_fields.php(11): Backend\Classes\WidgetBase->makePartial('_field-containe...', Array)
#8 /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php(272): include('/Users/casashoc...')
#9 /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php(103): Backend\Classes\WidgetBase->makeFileContents('/Users/casashoc...', Array)
#10 /Users/casashock/Documents/NovaProjects/solumat/modules/backend/widgets/form/partials/_form_tabs.php(63): Backend\Classes\WidgetBase->makePartial('_form_fields', Array)
#11 /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php(272): include('/Users/casashoc...')
#12 /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php(103): Backend\Classes\WidgetBase->makeFileContents('/Users/casashoc...', Array)
#13 /Users/casashock/Documents/NovaProjects/solumat/modules/backend/widgets/form/partials/_section.php(27): Backend\Classes\WidgetBase->makePartial('_form_tabs', Array)
#14 /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php(272): include('/Users/casashoc...')
#15 /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php(103): Backend\Classes\WidgetBase->makeFileContents('/Users/casashoc...', Array)
#16 /Users/casashock/Documents/NovaProjects/solumat/modules/backend/widgets/form/partials/_form.php(10): Backend\Classes\WidgetBase->makePartial('_section', Array)
#17 /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php(272): include('/Users/casashoc...')
#18 /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php(103): Backend\Classes\WidgetBase->makeFileContents('/Users/casashoc...', Array)
#19 /Users/casashock/Documents/NovaProjects/solumat/modules/backend/widgets/form/partials/_form-container.php(7): Backend\Classes\WidgetBase->makePartial('_form')
#20 /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php(272): include('/Users/casashoc...')
#21 /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php(103): Backend\Classes\WidgetBase->makeFileContents('/Users/casashoc...', Array)
#22 /Users/casashock/Documents/NovaProjects/solumat/modules/backend/widgets/Form.php(251): Backend\Classes\WidgetBase->makePartial('_form-container', Array)
#23 /Users/casashock/Documents/NovaProjects/solumat/modules/backend/behaviors/FormController.php(510): Backend\Widgets\Form->render(Array)
#24 [internal function]: Backend\Behaviors\FormController->formRender()
#25 /Users/casashock/Documents/NovaProjects/solumat/vendor/october/rain/src/Extension/ExtendableTrait.php(504): call_user_func_array(Array, Array)
#26 /Users/casashock/Documents/NovaProjects/solumat/vendor/october/rain/src/Extension/Extendable.php(55): October\Rain\Extension\Extendable->extendableCall('formRender', Array)
#27 /Users/casashock/Documents/NovaProjects/solumat/plugins/rainlab/blog/controllers/posts/create.htm(10): October\Rain\Extension\Extendable->__call('formRender', Array)
#28 /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php(272): include('/Users/casashoc...')
#29 /Users/casashock/Documents/NovaProjects/solumat/modules/system/traits/ViewMaker.php(117): Backend\Classes\Controller->makeFileContents('/Users/casashoc...')
#30 /Users/casashock/Documents/NovaProjects/solumat/modules/backend/classes/Controller.php(406): Backend\Classes\Controller->makeView('create')
#31 /Users/casashock/Documents/NovaProjects/solumat/modules/backend/classes/Controller.php(274): Backend\Classes\Controller->execPageAction('create', Array)
#32 /Users/casashock/Documents/NovaProjects/solumat/modules/backend/classes/BackendController.php(137): Backend\Classes\Controller->run('create', Array)
#33 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Backend\Classes\BackendController->run('rainlab/blog/po...')
#34 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction('run', Array)
#35 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Backend\Classes\BackendController), 'run')
#36 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#37 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Route->run()
#38 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#45 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#53 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#54 /Users/casashock/Documents/NovaProjects/solumat/vendor/october/rain/src/Router/CoreRouter.php(32): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#55 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#56 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#57 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /Users/casashock/Documents/NovaProjects/solumat/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#62 /Users/casashock/Documents/NovaProjects/solumat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#63 /Users/casashock/Documents/NovaProjects/solumat/index.php(42): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#64 /Users/casashock/.composer/vendor/laravel/valet/server.php(110): require('/Users/casashoc...')
#65 {main}
```

**Comment by daftspunk** [comment]
Even when forcing the rich editor in the blog plugin:

![image](https://github.com/rainlab/blog-plugin/assets/1392869/eec461e8-efea-4ae0-83e1-3a4f5e462d42)

The MLRichEditor appears to load fine:

![image](https://github.com/rainlab/blog-plugin/assets/1392869/282560f2-30af-42f0-a106-cb4dbeec3357)

Could it be caused by another plugin?

**Comment by Pixinside** [comment]
I deactivated the Rainlab.sitemap plugin and it worked on my local machine. 
But on my prod server I had deactivate the translate plugin. 
With the same plugin and settings... weird

**Comment by daftspunk** [comment]
Ah yes, I've taken a closer look at this...

The dedicated `_field_mlricheditor` is no longer used by the latest versions of OC and Translate plugin. It might suggest an old version of something used in conjunction with a new version. Most likely the RainLab.Blog plugin is not up to date.

I hope this helps.
